# ########################################################### #
# CashShop Plugin Developer: PopoGonry ( rhtjdsh35@gmail.com )
# ########################################################### #

# CashShop Plugin Config File #

# CashShop


CashShop-GUI-Display-Name: "캐시상점"